/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticatedTeamsImport } from './routes/_authenticated/teams'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedTeamsTeamIdRouteImport } from './routes/_authenticated/teams_/$teamId/route'
import { Route as AuthenticatedTeamsTeamIdIndexImport } from './routes/_authenticated/teams_/$teamId/index'
import { Route as AuthenticatedTeamsTeamIdMembersImport } from './routes/_authenticated/teams_/$teamId/members'
import { Route as AuthenticatedTeamsTeamIdJobsImport } from './routes/_authenticated/teams_/$teamId/jobs'
import { Route as AuthenticatedTeamsTeamIdJobCreateImport } from './routes/_authenticated/teams_/$teamId/job-create'
import { Route as AuthenticatedTeamsTeamIdJobsJobIdRecordImport } from './routes/_authenticated/teams_/$teamId/jobs_/$jobId/record'
import { Route as AuthenticatedTeamsTeamIdJobsJobIdJobUpdateImport } from './routes/_authenticated/teams_/$teamId/jobs_/$jobId/job-update'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedTeamsRoute = AuthenticatedTeamsImport.update({
  id: '/_authenticated/teams',
  path: '/teams',
  getParentRoute: () => rootRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedTeamsTeamIdRouteRoute =
  AuthenticatedTeamsTeamIdRouteImport.update({
    id: '/_authenticated/teams_/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => rootRoute,
  } as any)

const AuthenticatedTeamsTeamIdIndexRoute =
  AuthenticatedTeamsTeamIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeamsTeamIdRouteRoute,
  } as any)

const AuthenticatedTeamsTeamIdMembersRoute =
  AuthenticatedTeamsTeamIdMembersImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedTeamsTeamIdRouteRoute,
  } as any)

const AuthenticatedTeamsTeamIdJobsRoute =
  AuthenticatedTeamsTeamIdJobsImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedTeamsTeamIdRouteRoute,
  } as any)

const AuthenticatedTeamsTeamIdJobCreateRoute =
  AuthenticatedTeamsTeamIdJobCreateImport.update({
    id: '/job-create',
    path: '/job-create',
    getParentRoute: () => AuthenticatedTeamsTeamIdRouteRoute,
  } as any)

const AuthenticatedTeamsTeamIdJobsJobIdRecordRoute =
  AuthenticatedTeamsTeamIdJobsJobIdRecordImport.update({
    id: '/jobs_/$jobId/record',
    path: '/jobs/$jobId/record',
    getParentRoute: () => AuthenticatedTeamsTeamIdRouteRoute,
  } as any)

const AuthenticatedTeamsTeamIdJobsJobIdJobUpdateRoute =
  AuthenticatedTeamsTeamIdJobsJobIdJobUpdateImport.update({
    id: '/jobs_/$jobId/job-update',
    path: '/jobs/$jobId/job-update',
    getParentRoute: () => AuthenticatedTeamsTeamIdRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/teams_/$teamId': {
      id: '/_authenticated/teams_/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/teams_/$teamId/job-create': {
      id: '/_authenticated/teams_/$teamId/job-create'
      path: '/job-create'
      fullPath: '/teams/$teamId/job-create'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdJobCreateImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRouteImport
    }
    '/_authenticated/teams_/$teamId/jobs': {
      id: '/_authenticated/teams_/$teamId/jobs'
      path: '/jobs'
      fullPath: '/teams/$teamId/jobs'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdJobsImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRouteImport
    }
    '/_authenticated/teams_/$teamId/members': {
      id: '/_authenticated/teams_/$teamId/members'
      path: '/members'
      fullPath: '/teams/$teamId/members'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdMembersImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRouteImport
    }
    '/_authenticated/teams_/$teamId/': {
      id: '/_authenticated/teams_/$teamId/'
      path: '/'
      fullPath: '/teams/$teamId/'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdIndexImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRouteImport
    }
    '/_authenticated/teams_/$teamId/jobs_/$jobId/job-update': {
      id: '/_authenticated/teams_/$teamId/jobs_/$jobId/job-update'
      path: '/jobs/$jobId/job-update'
      fullPath: '/teams/$teamId/jobs/$jobId/job-update'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdJobsJobIdJobUpdateImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRouteImport
    }
    '/_authenticated/teams_/$teamId/jobs_/$jobId/record': {
      id: '/_authenticated/teams_/$teamId/jobs_/$jobId/record'
      path: '/jobs/$jobId/record'
      fullPath: '/teams/$teamId/jobs/$jobId/record'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdJobsJobIdRecordImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedTeamsTeamIdRouteRouteChildren {
  AuthenticatedTeamsTeamIdJobCreateRoute: typeof AuthenticatedTeamsTeamIdJobCreateRoute
  AuthenticatedTeamsTeamIdJobsRoute: typeof AuthenticatedTeamsTeamIdJobsRoute
  AuthenticatedTeamsTeamIdMembersRoute: typeof AuthenticatedTeamsTeamIdMembersRoute
  AuthenticatedTeamsTeamIdIndexRoute: typeof AuthenticatedTeamsTeamIdIndexRoute
  AuthenticatedTeamsTeamIdJobsJobIdJobUpdateRoute: typeof AuthenticatedTeamsTeamIdJobsJobIdJobUpdateRoute
  AuthenticatedTeamsTeamIdJobsJobIdRecordRoute: typeof AuthenticatedTeamsTeamIdJobsJobIdRecordRoute
}

const AuthenticatedTeamsTeamIdRouteRouteChildren: AuthenticatedTeamsTeamIdRouteRouteChildren =
  {
    AuthenticatedTeamsTeamIdJobCreateRoute:
      AuthenticatedTeamsTeamIdJobCreateRoute,
    AuthenticatedTeamsTeamIdJobsRoute: AuthenticatedTeamsTeamIdJobsRoute,
    AuthenticatedTeamsTeamIdMembersRoute: AuthenticatedTeamsTeamIdMembersRoute,
    AuthenticatedTeamsTeamIdIndexRoute: AuthenticatedTeamsTeamIdIndexRoute,
    AuthenticatedTeamsTeamIdJobsJobIdJobUpdateRoute:
      AuthenticatedTeamsTeamIdJobsJobIdJobUpdateRoute,
    AuthenticatedTeamsTeamIdJobsJobIdRecordRoute:
      AuthenticatedTeamsTeamIdJobsJobIdRecordRoute,
  }

const AuthenticatedTeamsTeamIdRouteRouteWithChildren =
  AuthenticatedTeamsTeamIdRouteRoute._addFileChildren(
    AuthenticatedTeamsTeamIdRouteRouteChildren,
  )

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/sign-in': typeof authSignInRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRouteRouteWithChildren
  '/teams/$teamId/job-create': typeof AuthenticatedTeamsTeamIdJobCreateRoute
  '/teams/$teamId/jobs': typeof AuthenticatedTeamsTeamIdJobsRoute
  '/teams/$teamId/members': typeof AuthenticatedTeamsTeamIdMembersRoute
  '/teams/$teamId/': typeof AuthenticatedTeamsTeamIdIndexRoute
  '/teams/$teamId/jobs/$jobId/job-update': typeof AuthenticatedTeamsTeamIdJobsJobIdJobUpdateRoute
  '/teams/$teamId/jobs/$jobId/record': typeof AuthenticatedTeamsTeamIdJobsJobIdRecordRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/sign-in': typeof authSignInRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/teams/$teamId/job-create': typeof AuthenticatedTeamsTeamIdJobCreateRoute
  '/teams/$teamId/jobs': typeof AuthenticatedTeamsTeamIdJobsRoute
  '/teams/$teamId/members': typeof AuthenticatedTeamsTeamIdMembersRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdIndexRoute
  '/teams/$teamId/jobs/$jobId/job-update': typeof AuthenticatedTeamsTeamIdJobsJobIdJobUpdateRoute
  '/teams/$teamId/jobs/$jobId/record': typeof AuthenticatedTeamsTeamIdJobsJobIdRecordRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/login': typeof LoginRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/_authenticated/teams_/$teamId': typeof AuthenticatedTeamsTeamIdRouteRouteWithChildren
  '/_authenticated/teams_/$teamId/job-create': typeof AuthenticatedTeamsTeamIdJobCreateRoute
  '/_authenticated/teams_/$teamId/jobs': typeof AuthenticatedTeamsTeamIdJobsRoute
  '/_authenticated/teams_/$teamId/members': typeof AuthenticatedTeamsTeamIdMembersRoute
  '/_authenticated/teams_/$teamId/': typeof AuthenticatedTeamsTeamIdIndexRoute
  '/_authenticated/teams_/$teamId/jobs_/$jobId/job-update': typeof AuthenticatedTeamsTeamIdJobsJobIdJobUpdateRoute
  '/_authenticated/teams_/$teamId/jobs_/$jobId/record': typeof AuthenticatedTeamsTeamIdJobsJobIdRecordRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/sign-in'
    | '/teams'
    | '/teams/$teamId'
    | '/teams/$teamId/job-create'
    | '/teams/$teamId/jobs'
    | '/teams/$teamId/members'
    | '/teams/$teamId/'
    | '/teams/$teamId/jobs/$jobId/job-update'
    | '/teams/$teamId/jobs/$jobId/record'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/sign-in'
    | '/teams'
    | '/teams/$teamId/job-create'
    | '/teams/$teamId/jobs'
    | '/teams/$teamId/members'
    | '/teams/$teamId'
    | '/teams/$teamId/jobs/$jobId/job-update'
    | '/teams/$teamId/jobs/$jobId/record'
  id:
    | '__root__'
    | '/login'
    | '/(auth)/sign-in'
    | '/_authenticated/teams'
    | '/_authenticated/teams_/$teamId'
    | '/_authenticated/teams_/$teamId/job-create'
    | '/_authenticated/teams_/$teamId/jobs'
    | '/_authenticated/teams_/$teamId/members'
    | '/_authenticated/teams_/$teamId/'
    | '/_authenticated/teams_/$teamId/jobs_/$jobId/job-update'
    | '/_authenticated/teams_/$teamId/jobs_/$jobId/record'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  authSignInRoute: typeof authSignInRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
  AuthenticatedTeamsTeamIdRouteRoute: typeof AuthenticatedTeamsTeamIdRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  authSignInRoute: authSignInRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
  AuthenticatedTeamsTeamIdRouteRoute:
    AuthenticatedTeamsTeamIdRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/login",
        "/(auth)/sign-in",
        "/_authenticated/teams",
        "/_authenticated/teams_/$teamId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/_authenticated/teams": {
      "filePath": "_authenticated/teams.tsx"
    },
    "/_authenticated/teams_/$teamId": {
      "filePath": "_authenticated/teams_/$teamId/route.tsx",
      "children": [
        "/_authenticated/teams_/$teamId/job-create",
        "/_authenticated/teams_/$teamId/jobs",
        "/_authenticated/teams_/$teamId/members",
        "/_authenticated/teams_/$teamId/",
        "/_authenticated/teams_/$teamId/jobs_/$jobId/job-update",
        "/_authenticated/teams_/$teamId/jobs_/$jobId/record"
      ]
    },
    "/_authenticated/teams_/$teamId/job-create": {
      "filePath": "_authenticated/teams_/$teamId/job-create.tsx",
      "parent": "/_authenticated/teams_/$teamId"
    },
    "/_authenticated/teams_/$teamId/jobs": {
      "filePath": "_authenticated/teams_/$teamId/jobs.tsx",
      "parent": "/_authenticated/teams_/$teamId"
    },
    "/_authenticated/teams_/$teamId/members": {
      "filePath": "_authenticated/teams_/$teamId/members.tsx",
      "parent": "/_authenticated/teams_/$teamId"
    },
    "/_authenticated/teams_/$teamId/": {
      "filePath": "_authenticated/teams_/$teamId/index.tsx",
      "parent": "/_authenticated/teams_/$teamId"
    },
    "/_authenticated/teams_/$teamId/jobs_/$jobId/job-update": {
      "filePath": "_authenticated/teams_/$teamId/jobs_/$jobId/job-update.tsx",
      "parent": "/_authenticated/teams_/$teamId"
    },
    "/_authenticated/teams_/$teamId/jobs_/$jobId/record": {
      "filePath": "_authenticated/teams_/$teamId/jobs_/$jobId/record.tsx",
      "parent": "/_authenticated/teams_/$teamId"
    }
  }
}
ROUTE_MANIFEST_END */
